responses = {
    # 💻 Technology
    "what is artificial intelligence": "AI is the ability of machines to mimic human intelligence.",
    "what is blockchain": "Blockchain is a distributed ledger technology, best known for powering cryptocurrencies.",
    "what is cybersecurity": "Cybersecurity protects systems and data from digital attacks.",
    "what is devops": "DevOps blends software development and IT operations for faster delivery.",
    "how to learn programming": "Start with Python. Practice daily, build projects, and join a developer community!",
    "what is sql": "SQL stands for Structured Query Language and is used to manage databases.",
    "what is docker": "Docker is a platform to develop, ship, and run applications in containers.",
    "what is github": "GitHub is a platform to host, collaborate on, and review code projects.",
    "what is terminal": "The terminal is a command-line interface used to interact with the computer using text commands.",
    "what is operating system": "An OS is software that manages computer hardware and software resources.",
    "what is html": "HTML is the language for creating web pages.",
    "what is css": "CSS styles your HTML pages — it makes things look pretty!",
    "what is api": "An API is a way for programs to talk to each other.",
    "what is cloud computing": "It's delivering computing services over the internet like storage and processing.",
    "what is openai": "OpenAI is the organization that created me — ChatGPT!",
    "what is machine learning": "Machine learning is a branch of AI that teaches computers to learn from data.",

    # 💖 Love & Relationships
    "how to express love": "Speak from the heart, be honest, and show it through actions 💖",
    "how to handle heartbreak": "Give yourself time to heal, talk to loved ones, and focus on self-care.",
    "is love real": "Yes, love is a powerful and beautiful human emotion.",
    "how to propose": "Be sincere, choose a meaningful moment, and speak your heart 💍",
    "what is friendship": "A bond of trust, support, laughter, and care between people 🤝",
    "how to deal with long distance": "Communicate regularly, share little things, and make time for virtual dates ❤️",
    "i love you": "Aww, you're sweet! I'm just a bot, but I’m flattered ❤️",
    "do you love me": "I like chatting with you a lot, if that counts 😉",
    "how to impress someone": "Be yourself, be kind, and listen — authenticity goes a long way.",
    "i miss someone": "Missing someone shows they matter. Reach out if you can 💌",

    # 🌐 General Knowledge
    "what is the tallest mountain": "Mount Everest, standing at 8,848 meters (29,029 feet).",
    "what is the fastest animal": "The peregrine falcon can dive at speeds over 240 mph!",
    "who was albert einstein": "A brilliant physicist known for the theory of relativity.",
    "who invented the telephone": "Alexander Graham Bell in 1876.",
    "what is democracy": "Democracy is a system where people elect representatives to make decisions.",
    "what is the internet": "A global network connecting computers worldwide for sharing information.",
    "what is the capital of india": "The capital of India is New Delhi.",
    "who is the prime minister of india": "As of now, it’s Narendra Modi.",
    "what is water made of": "Water is made of two hydrogen atoms and one oxygen atom — H₂O.",
    "how many continents are there": "There are 7 continents in the world.",

    # 🧑‍💼 Career & Productivity
    "how to be productive": "Set goals, avoid distractions, and take breaks!",
    "how to prepare for an interview": "Research the company, practice answers, and be confident.",
    "resume tips": "Keep it concise, use bullet points, and tailor it to the job description.",
    "how to focus": "Use techniques like Pomodoro, eliminate distractions, and stay hydrated.",
    "what is freelancing": "Freelancing means working independently for clients, often remotely.",
    "remote work tips": "Have a clear routine, dedicated space, and take breaks to move around.",
    "how to work from home effectively": "Stick to a routine, dress up, and create a workspace.",
    "how to set goals": "Use SMART goals — Specific, Measurable, Achievable, Relevant, Time-bound.",
    "how to deal with failure": "Learn from it, adjust your approach, and keep moving forward.",

    # 🎮 Fun & Entertainment
    "recommend a movie": "Try 'Inception' if you like sci-fi and mind-bending stories 🎬",
    "tell me something cool": "Octopuses have three hearts and blue blood!",
    "who is your favorite superhero": "Iron Man is pretty cool — techy, smart, and snarky 🦾",
    "what games do you like": "I'm into word games and logic puzzles — digital style! 🧠",
    "fun things to do": "Read, walk, journal, game, chat with friends, or learn something new!",
    "tell me a joke": "Why did the computer go to therapy? It had a hard drive! 😂",
    "play a game": "Sure! How about a riddle or a number guessing game?",
    "who is the best cricketer": "That’s subjective! But Virat Kohli and Sachin Tendulkar are legends.",
    "suggest a song": "‘Shape of You’ by Ed Sheeran is always a good vibe 🎶",

    # 🙋‍♂️ Self-help & Mental Health
    "how to reduce stress": "Breathe deeply, go for a walk, talk to someone, or listen to calming music 🎵",
    "i feel overwhelmed": "Break tasks into small parts. You’ve got this, one step at a time 💪",
    "how to be confident": "Believe in your skills, speak kindly to yourself, and practice regularly.",
    "how to improve myself": "Read books, build healthy habits, reflect often, and keep learning.",
    "i feel lonely": "You're not alone. Reach out to a friend or family member — or keep chatting with me! 💙",
    "i'm anxious": "It’s okay to feel that way. Try grounding exercises or talk to someone you trust.",
    "how to handle depression": "You're not alone — talking to a professional is always a strong first step.",
    "how to be happy": "Focus on gratitude, build good relationships, and do what makes you feel fulfilled.",

    # 📚 Learning & Education
    "how to study better": "Study in short focused sessions, use active recall, and take breaks.",
    "how to read faster": "Try skimming for structure first, then focus. Practice helps!",
    "best books to read": "For productivity: 'Atomic Habits'. For fiction: 'The Alchemist'.",
    "what is coding": "Coding is writing instructions that computers can understand and run.",
    "how to learn data science": "Start with Python, learn pandas and NumPy, then move to ML concepts.",
    "what is artificial neural network": "It’s a system of algorithms inspired by the human brain for AI tasks.",
    "what is a variable in programming": "It’s a container used to store data that can change.",
    "difference between frontend and backend": "Frontend is what users see. Backend handles data and server logic.",

    # 🧘 Motivation & Quotes
    "motivate me": "Every expert was once a beginner. Keep going 💡",
    "give me a quote": "“Success is not final, failure is not fatal: It is the courage to continue that counts.” – Winston Churchill",
    "i feel like giving up": "You’ve come this far. That alone is proof of your strength 💪",
    "how to stay motivated": "Set clear goals, track progress, and celebrate small wins!",
    "is failure bad": "No! Failure is a stepping stone to success. Learn, adapt, and try again.",
    "how to stay consistent": "Create a routine, start small, and stay accountable.",
    "daily motivation": "You don’t have to be perfect, just consistent 💪",

    # 💡 Random
    "how tall is the eiffel tower": "About 300 meters (984 feet) tall.",
    "can dogs eat chocolate": "No! Chocolate is toxic to dogs.",
    "what is time": "Time is a measure of change or events occurring in sequence.",
    "what's your favorite color": "I like electric blue — it's very… digital 💙",
    "can you feel emotions": "I understand emotions, but I don't feel them — I'm all logic and code!",
    "how to make a chatbot": "Use Python, Flask or Django, and something like GPT or rule-based logic!",
    "do you sleep": "Not really, I’m available 24/7! 🛌⚡",
    "what is your age": "I'm timeless — born from the cloud ☁️✨",
    "what's your name": "I'm your friendly chatbot assistant 🤖",
    "who created you": "I was developed by awesome programmers using OpenAI!"
}
