# Generated by Django 5.1 on 2024-08-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='m', max_length=1)),
                ('value', models.PositiveIntegerField()),
                ('medicine_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Time_Unit_Table',
            },
        ),
    ]
