# Generated by Django 5.0.4 on 2024-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FatMugAssignmentApp', '0003_delete_person_alter_historicalperformance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'Students_Table',
            },
        ),
    ]
